export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-4xl mx-auto bg-white rounded-xl shadow-lg p-8">
        <h1 className="text-4xl font-bold text-gray-900 mb-6">Terms of Service</h1>
        <p className="text-sm text-gray-600 mb-8">Last updated: December 15, 2024</p>

        <div className="prose prose-purple max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              By accessing or using Valley Somm ("Service"), you agree to be bound by these Terms of Service. 
              If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Description of Service</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              Valley Somm is an AI-powered wine trail planning service that:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Generates personalized winery recommendations</li>
              <li>Creates custom itineraries for Yadkin Valley wine tours</li>
              <li>Provides information about wineries, wines, and experiences</li>
              <li>Allows sharing of trails via unique URLs</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">3. Age Requirement</h2>
            <p className="text-gray-700 leading-relaxed">
              You must be at least 21 years old to use Valley Somm. By using the Service, you represent that you are of legal drinking age in your jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Use of Service</h2>
            <h3 className="text-xl font-semibold text-gray-800 mb-2">4.1 Permitted Use</h3>
            <p className="text-gray-700 leading-relaxed mb-4">You may use Valley Somm to:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Plan personal wine trails</li>
              <li>Share trails with friends and family</li>
              <li>Discover Yadkin Valley wineries</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-2">4.2 Prohibited Use</h3>
            <p className="text-gray-700 leading-relaxed mb-4">You may NOT:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Use the Service for commercial purposes without permission</li>
              <li>Scrape, copy, or download large amounts of data</li>
              <li>Reverse engineer or attempt to extract source code</li>
              <li>Submit false, misleading, or harmful information</li>
              <li>Interfere with or disrupt the Service</li>
              <li>Use automated tools (bots) without authorization</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">5. AI-Generated Recommendations</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              <strong>Important Disclaimer:</strong>
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Recommendations are generated by AI and may not be perfect</li>
              <li>We do not guarantee availability, hours, or specific offerings at wineries</li>
              <li>Always verify details directly with wineries before visiting</li>
              <li>Driving routes are estimates - use GPS navigation for accuracy</li>
              <li>Wine recommendations are suggestions, not professional sommelier advice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Third-Party Content</h2>
            <p className="text-gray-700 leading-relaxed">
              Valley Somm provides links to third-party websites (wineries). We are not responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Accuracy of information on winery websites</li>
              <li>Availability or quality of wines and services</li>
              <li>Pricing, reservations, or booking policies</li>
              <li>Privacy practices of third-party sites</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Disclaimer of Warranties</h2>
            <p className="text-gray-700 leading-relaxed">
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. We do not warrant that:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>The Service will be uninterrupted or error-free</li>
              <li>AI recommendations will be accurate or suitable for your needs</li>
              <li>Winery information will be current or complete</li>
              <li>The Service will meet your expectations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Limitation of Liability</h2>
            <p className="text-gray-700 leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, Valley Somm shall not be liable for:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Indirect, incidental, or consequential damages</li>
              <li>Loss of profits, data, or business opportunities</li>
              <li>Issues arising from winery visits or wine purchases</li>
              <li>Accidents, injuries, or property damage during wine tours</li>
              <li>Quality of wines, services, or experiences at wineries</li>
            </ul>
            <p className="text-gray-700 leading-relaxed mt-4">
              <strong>You are responsible for:</strong> Safe transportation (designated driver or ride service), 
              verifying winery hours and policies, and all decisions made during your wine trail.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Responsible Drinking</h2>
            <p className="text-gray-700 leading-relaxed">
              <strong>Valley Somm strongly encourages responsible alcohol consumption:</strong>
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Never drink and drive - use a designated driver or ride service</li>
              <li>Know your limits and drink responsibly</li>
              <li>Wineries may refuse service to intoxicated guests</li>
              <li>Follow all local laws and regulations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Intellectual Property</h2>
            <p className="text-gray-700 leading-relaxed">
              All content on Valley Somm (design, code, logos, text) is owned by Valley Somm or licensed. 
              You may not copy, reproduce, or distribute our content without permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">11. Changes to Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              We reserve the right to modify these terms at any time. Continued use of the Service after 
              changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">12. Contact</h2>
            <p className="text-gray-700 leading-relaxed">
              Questions about these terms? Contact us at legal@valleysomm.com
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-200">
          <a
            href="/"
            className="inline-block bg-purple-600 text-white px-8 py-3 rounded-xl font-semibold hover:bg-purple-700 transition-colors"
          >
            Back to Home
          </a>
        </div>
      </div>
    </div>
  );
}